export const SET_LOADING = 'SET_LOADING'

export const REGISTER_USER_SUCCESS = 'REGISTER_USER_SUCCESS'
export const REGISTER_USER_ERROR = 'REGISTER_USER_ERROR'


export const FETCH_TRAVELS_SUCCESS = 'FETCH_TRAVELS_SUCCESS'
export const FETCH_TRAVELS_ERROR = 'FETCH_TRAVELS_ERROR'

export const SET_USER = 'SET_USER'


export const CREATE_TRAVEL_SUCCESS = 'CREATE_TRAVEL_SUCCESS'
export const CREATE_TRAVEL_ERROR = 'CREATE_TRAVEL_ERROR'


export const DELETE_TRAVEL_SUCCESS = 'DELETE_TRAVEL_SUCCESS'
export const DELETE_TRAVEL_ERROR = 'DELETE_TRAVEL_ERROR'


export const UPDATE_TRAVEL_SUCCESS = 'UPDATE_TRAVEL_SUCCESS'
export const UPDATE_TRAVEL_ERROR = 'UPDATE_TRAVEL_ERROR'

export const LOGOUT_USER = 'LOGOUT_USER'

